# Making changes? https://github.com/nektos/act may help you test locally

name: "Publish main branch"

# TODO: Support multiple versions in parallel
on: 
  push:
    branches:
    - "master"
    - "main/*"

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-artifact.yaml
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: "checkout"
      uses: "actions/checkout@v2"
    - name: "restore artifact"
      uses: "actions/download-artifact@v2"
      with: 
        name: docs-html
        path: build/html
    - name: "publish to pages"
      uses: "JamesIves/github-pages-deploy-action@v4.2.5"
      with:
        branch: "gh-pages"
        folder: "build/html"
        single-commit: true

